language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - freebsd

arch:
  - arm64
  - amd64
  - ppc64le

git:
  depth: false
  quiet: true

script: ./bootstrap && ./configure --disable-term-size --without-readline && make

after_success:
  - make check
  - sudo make install

notifications:
  email:
    on_success: never
    on_failure: never

# vim:set et sw=2 ts=2:
